In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Reading dataset
df = pd.read_csv("../datasets/ebay_mens_perfume.csv")

In [3]:
df

,brand,title,type,price,priceWithCurrency,available,availableText,sold,lastUpdated,itemLocation
0,Dior,Christian Dior Sauvage Men's EDP 3.4 oz Fragra...,Eau de Parfum,84.99,US $84.99/ea,10.0,More than 10 available / 116 sold,116.0,"May 24, 2024 10:03:04 PDT","Allen Park, Michigan, United States"
1,AS SHOW,A-v-entus Eau de Parfum 3.3 oz 100ML Millesime...,Eau de Parfum,109.99,US $109.99,8.0,8 available / 48 sold,48.0,"May 23, 2024 23:07:49 PDT","Atlanta, Georgia, Canada"
2,Unbranded,HOGO BOSS cologne For Men 3.4 oz,Eau de Toilette,100.00,US $100.00,10.0,More than 10 available / 27 sold,27.0,"May 22, 2024 21:55:43 PDT","Dearborn, Michigan, United States"
3,Giorgio Armani,Acqua Di Gio by Giorgio Armani 6.7 Fl oz Eau D...,Eau de Toilette,44.99,US $44.99/ea,2.0,2 available / 159 sold,159.0,"May 24, 2024 03:30:43 PDT","Reinholds, Pennsylvania, United States"
4,Lattafa,Lattafa Men's Hayaati Al Maleky EDP Spray 3.4 ...,Fragrances,16.91,US $16.91,NaN,Limited quantity available / 156 sold,156.0,"May 24, 2024 07:56:25 PDT","Brooklyn, New York, United States"
...,...,...,...,...,...,...,...,...,...,...
995,GUESS,Guess 1981 by Guess cologne for men EDT 3.3 / ...,Eau de Toilette,20.28,US $20.28/ea,45.0,"45 available / 1,613 sold",1613.0,"May 24, 2024 08:14:07 PDT","Dallas, Texas, United States"
996,Armaf,Club de Nuit Intense by Armaf cologne for men ...,Eau de Toilette,30.58,US $30.58,10.0,More than 10 available / 31 sold,31.0,"May 23, 2024 08:39:30 PDT",United States
997,Paco Rabanne,Invictus by Paco Rabanne for Men EDT Spray 3.4...,Eau de Toilette,39.99,US $39.99/ea,2.0,2 available / 305 sold,305.0,"May 23, 2024 15:27:18 PDT","Jamaica, New York, United States"
998,Lomani,"Lomani EDT Cologne 3.4 oz Men - Authentic, Bra...",Eau de Toilette,9.99,US $9.99/ea,2.0,2 available / 22 sold,22.0,"May 20, 2024 13:20:54 PDT","Lincoln Park, Michigan, United States"
999,Estee Lauder,Beyond Paradise by Estee Lauder for Men Cologn...,Cologne spray,17.49,US $17.49/ea,10.0,More than 10 available / 24 sold,24.0,"Feb 28, 2024 07:27:01 PST","Keyport, New Jersey, United States"

In [10]:
df.shape

(1000, 10)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   brand              999 non-null    object
 1   title              1000 non-null   object
 2   type               997 non-null    object
 3   price              1000 non-null   float64
 4   priceWithCurrency  1000 non-null   object
 5   available          889 non-null    float64
 6   availableText      997 non-null    object
 7   sold               994 non-null    float64
 8   lastUpdated        947 non-null    object
 9   itemLocation       1000 non-null   object
dtypes: float64(3), object(7)
memory usage: 78.2+ KB

In [7]:
df.describe()

             price   available          sold
count  1000.000000  889.000000    994.000000
mean     46.481200   20.046119    766.266600
std      35.527862   61.547985   3200.971733
min       3.000000    2.000000      1.000000
25%      22.990000    5.000000     14.000000
50%      35.710000   10.000000     49.500000
75%      59.000000   10.000000    320.500000
max     259.090000  842.000000  54052.000000

In [4]:
df.isnull().sum()

brand                  1
title                  0
type                   3
price                  0
priceWithCurrency      0
available            111
availableText          3
sold                   6
lastUpdated           53
itemLocation           0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [18]:
df[df['title'].duplicated()]

,brand,title,type,price,priceWithCurrency,available,availableText,sold,lastUpdated,itemLocation
90,Unbranded,SEALED NEW CUPID 2.0 HYPNOSIS MEN’S PHEROMONE ...,Perfume,14.99,US $14.99,10.0,More than 10 available / 358 sold,358.0,"May 24, 2024 09:56:14 PDT","Houston, Texas, United States"
95,Unbranded,Hawas for him Eau De Parfum By Rasasi 100ml 3....,/,15.89,US $15.89,6.0,6 available / 8 sold,8.0,"May 22, 2024 22:34:16 PDT","shanghai, China"
96,Giorgio Armani,Giorgio Armani Acqua Di Gio 6.7oz / 200ml Men'...,Eau de Toilette,59.99,US $59.99,10.0,More than 10 available / 14 sold,14.0,"May 21, 2024 07:50:36 PDT","Hamtramck, Michigan, United States"
116,Unbranded,SEALED NEW CUPID 2.0 HYPNOSIS MEN’S PHEROMONE ...,Perfume,15.99,US $15.99,10.0,More than 10 available / 14 sold,14.0,"May 24, 2024 01:46:35 PDT","Houston, Texas, United States"
136,SECERTMU,New 2024 Sexy Cologne Cupid Hypnosis Long Last...,Perfume,6.97,US $6.97,10.0,More than 10 available / 803 sold,803.0,"May 21, 2024 19:20:13 PDT","San Francisco, California, United States"
150,Unbranded,Hawas for him Eau De Parfum By Rasasi 100ml 3....,Perfume,17.99,US $17.99,10.0,More than 10 available / 3 sold,3.0,"May 23, 2024 17:06:03 PDT","Shenzhen, China"
166,AS PICTURE SHOWN,Silver Mountain Water Eau De Parfum 3.3 / 3.4 ...,Eau de Parfum,125.99,US $125.99,NaN,Last One / 15 sold,15.0,"May 24, 2024 01:04:08 PDT","Livingston Manor, New York, United States"
210,Unbranded,YSL Yves Saint Laurent Y Eau de Perfume Spray ...,Y,49.99,US $49.99/ea,8.0,8 available / 68 sold,68.0,"May 19, 2024 18:38:36 PDT","New Jersey, United States"
214,Ralph Lauren,Polo Double Black 4.2 oz by Ralph Lauren Mens ...,Eau de Toilette,44.99,US $44.99/ea,6.0,6 available / 14 sold,14.0,"May 21, 2024 23:16:01 PDT","Warren, Michigan, United States"
223,fragrance,YSL Yves Saint Laurent Y Eau de Perfume Spray ...,Eau de Parfum,46.99,US $46.99,2.0,2 available / 3 sold,3.0,"May 24, 2024 00:24:54 PDT","New City, New York, United States"
239,Unbranded,1/2PCS 50ml Men's Pheromone-Cupid Infused Perf...,Perfume,12.98,US $12.98,10.0,10 available / 103 sold,103.0,"May 24, 2024 10:10:30 PDT","Perth Amboy, New Jersey, United States"
275,Paco Rabanne,1 Million by Paco Rabanne 3.4 Fl oz / 100 ml P...,PARFUM,69.99,US $69.99/ea,9.0,9 available / 2 sold,2.0,"May 24, 2024 05:54:34 PDT","Warren, Michigan, United States"
286,Dior,Dior SAUVAGE by Christian Dior EDT Men 100 ml ...,Eau de Toilette,84.99,US $84.99/ea,10.0,More than 10 available / 51 sold,51.0,"May 06, 2024 04:40:12 PDT","Sterling Heights, Michigan, United States"
287,Abercrombie & Fitch,Abercrombie & Fitch Fierce 3.4 oz /100ml Eau D...,Eau de Cologne,38.99,US $38.99/ea,10.0,More than 10 available / 919 sold,919.0,"May 24, 2024 08:09:49 PDT","Detroit, Michigan, United States"
300,Unbranded,SEALED NEW CUPID HYPNOSIS MEN’S PHEROMONE COLO...,Perfume,15.99,US $15.99,10.0,More than 10 available / 7 sold,7.0,"May 22, 2024 19:01:20 PDT","Houston, Texas, United States"
336,Givenchy,Givenchy Gentleman 3.3oz.Eau de Toilette INTEN...,Eau de Toilette Intense,59.00,US $59.00/ea,10.0,10 available / 601 sold,601.0,"May 24, 2024 09:57:09 PDT","Katy, Texas, United States"
351,Unbranded,1/2PCS 50ml Men's Pheromone-Cupid Infused Perf...,Perfume,14.60,US $14.60,5.0,5 available / 94 sold,94.0,"May 22, 2024 23:30:09 PDT","Toronto, Ontario, Canada"
392,Unbranded,Hawas for him Eau De Parfum By Rasasi 100ml 3....,Perfume,21.99,US $21.99/ea,10.0,More than 10 available / 2 sold,2.0,"May 23, 2024 20:05:17 PDT","Shenzhen, China"
448,As Show,YSL Yves Saint Laurent Y Eau de Perfume Spray ...,Eau de Parfum,39.99,US $39.99/ea,8.0,8 available / 10 sold,10.0,"May 19, 2024 18:09:04 PDT","Dayton,New Jersey, Hong Kong"
490,Valentino,Valentino Uomo Born In Roma Coral Fantasy 3.4 ...,Eau de Toilette,103.98,US $103.98,NaN,Limited quantity available / 350 sold,350.0,"May 22, 2024 16:56:40 PDT","Hackensack, New Jersey, United States"
499,Kenneth Cole,KENNETH COLE BLACK Cologne for Men 3.4 oz EDT ...,Eau de Toilette,24.15,US $24.15/ea,10.0,More than 10 available / 14 sold,14.0,NaN,"Miami, Florida, United States"
513,Coach,Coach Green by Coach cologne for men EDT 3.3 /...,Eau de Toilette,41.99,US $41.99/ea,15.0,15 available / 248 sold,248.0,"May 24, 2024 07:21:29 PDT","Dallas, Texas, United States"
517,HERMÈS,Terre D'Hermes by Hermes cologne for men EDT 3...,Eau de Toilette,64.88,US $64.88/ea,16.0,16 available / 292 sold,292.0,"May 20, 2024 18:27:48 PDT","Dallas, Texas, United States"
523,Giorgio Armani,Giorgio Armani Aqua Di Gio Men's 3.4 oz EDT Cl...,Eau de Toilette,29.99,US $29.99/ea,9.0,9 available / 6 sold,6.0,"May 24, 2024 05:51:42 PDT","Warren, Michigan, United States"
584,Giorgio Armani,"Armani Code by Giorgio Armani, 4.2 oz Parfum S...",Gift Sets,94.43,US $94.43/ea,10.0,More than 10 available / 98 sold,98.0,"May 23, 2024 15:19:07 PDT","Edison, New Jersey, United States"
606,Milestone Perfumes,Intimation By Milestone Eau de Parfum 3.4 oz Men,NaN,19.89,US $19.89,10.0,More than 10 available / 21 sold,21.0,"May 24, 2024 10:13:17 PDT","Miami, Florida, United States"
642,Davidoff,Cool Water by Davidoff 4.2 oz EDT Cologne for ...,Eau de Toilette,25.23,US $25.23/ea,NaN,"Limited quantity available / 40,130 sold",40130.0,"May 24, 2024 05:18:15 PDT","Hackensack, New Jersey, United States"
650,Paco Rabanne,Phantom by Paco Rabanne 3.4 oz EDT Cologne for...,Eau de Toilette,70.08,US $70.08/ea,NaN,"Limited quantity available / 1,165 sold",1165.0,"May 23, 2024 16:28:06 PDT","Hackensack, New Jersey, United States"
688,SECERTMU,New 2024 Sexy Cologne Cupid Hypnosis Long Last...,Perfume,6.96,US $6.96,10.0,More than 10 available / 102 sold,102.0,"May 18, 2024 16:15:46 PDT","San Francisco, California, United States"
749,Unbranded,Men's Pheromone-Infused Perfume Cupid Hypnosis...,Perfume,15.99,US $15.99,10.0,More than 10 available / 65 sold,65.0,"May 22, 2024 14:08:35 PDT","Houston, Texas, United States"
780,Giorgio Armani,"Acqua di Gio by Giorgio Armani for Men, Eau d...",Eau de Toilette,51.99,US $51.99/ea,9.0,9 available / 28 sold,28.0,"Apr 23, 2024 04:55:18 PDT","Houston, Texas, United States"
813,Giorgio Armani,Armani Code By Giorgio Armani EDT for Men 4.2 ...,Eau de Toilette,37.95,US $37.95/ea,9.0,9 available / 20 sold,20.0,"May 20, 2024 05:50:34 PDT","Warren, Michigan, United States"
829,Zara,ZARA Sunrise On The Red Sand Dunes (Mylene Alr...,Eau de Parfum,48.97,US $48.97,4.0,4 available / 30 sold,30.0,"May 13, 2024 02:58:59 PDT","Matosinhos, Portugal"
846,Unbranded,New 2024 Sexy Cologne Cupid Hypnosis Long Last...,Fragrance Rolling Ball,10.99,US $10.99,10.0,More than 10 available / 38 sold,38.0,"May 20, 2024 23:42:53 PDT","Los Angeles, California, United States"