In [68]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [69]:
# Reading dataset
df_men = pd.read_csv("../datasets/ebay_mens_perfume.csv")
df_women = pd.read_csv("../datasets/ebay_womens_perfume.csv")

In [70]:
df_men["gender"] = "Men"
df_women["gender"] = "Women"

In [71]:
df = pd.concat([df_men, df_women], ignore_index=True)

In [94]:
pd.set_option('display.max_colwidth', None)

In [73]:
df

,brand,title,type,price,priceWithCurrency,available,availableText,sold,lastUpdated,itemLocation,gender
0,Dior,Christian Dior Sauvage Men's EDP 3.4 oz Fragrance Spray,Eau de Parfum,84.99,US $84.99/ea,10.0,More than 10 available / 116 sold,116.0,"May 24, 2024 10:03:04 PDT","Allen Park, Michigan, United States",Men
1,AS SHOW,A-v-entus Eau de Parfum 3.3 oz 100ML Millesime EDP Col-ogne for Men New In Box,Eau de Parfum,109.99,US $109.99,8.0,8 available / 48 sold,48.0,"May 23, 2024 23:07:49 PDT","Atlanta, Georgia, Canada",Men
2,Unbranded,HOGO BOSS cologne For Men 3.4 oz,Eau de Toilette,100.00,US $100.00,10.0,More than 10 available / 27 sold,27.0,"May 22, 2024 21:55:43 PDT","Dearborn, Michigan, United States",Men
3,Giorgio Armani,Acqua Di Gio by Giorgio Armani 6.7 Fl oz Eau De Toilette Spray Men' New & Sealed,Eau de Toilette,44.99,US $44.99/ea,2.0,2 available / 159 sold,159.0,"May 24, 2024 03:30:43 PDT","Reinholds, Pennsylvania, United States",Men
4,Lattafa,Lattafa Men's Hayaati Al Maleky EDP Spray 3.4 oz Fragrances 6291108734056,Fragrances,16.91,US $16.91,NaN,Limited quantity available / 156 sold,156.0,"May 24, 2024 07:56:25 PDT","Brooklyn, New York, United States",Men
...,...,...,...,...,...,...,...,...,...,...,...
1995,Avon,Avon Far Away Infinity Eau de Parfum 1.7 fl. oz. NIB/Free Travel Spray,Eau de Parfum,13.89,US $13.89,10.0,More than 10 available / 157 sold,157.0,"May 16, 2024 22:35:29 PDT","West Palm Beach, Florida, United States",Women
1996,Mancera,Roses Greedy by Mancera perfume for unisex EDP 4 / 4.0 oz New in Box,Eau de Parfum,57.85,US $57.85/ea,33.0,33 available / 58 sold,58.0,"May 24, 2024 08:03:11 PDT","Dallas, Texas, United States",Women
1997,Unbranded,"Sweet Tooth Eau de Parfum, Perfume for Women, 1 fl oz",1,30.96,US $30.96,2.0,2 available / 3 sold,3.0,"May 17, 2024 23:16:41 PDT","New York, New York, United States",Women
1998,Juliette Has A Gun,MMMM BY Juliette Has A Gun perfume for her EDP 3.3 / 3.4 oz New in Box,Eau de Perfume,53.99,US $53.99/ea,3.0,3 available / 117 sold,117.0,"May 13, 2024 22:19:34 PDT","Dallas, Texas, United States",Women
1999,Paris Hilton,PARIS HILTON ELECTRIFY for Women Cologne 3.4 oz 100 ml Eau de Parfum Spray UNBOX,Eau de Parfum,14.99,US $14.99/ea,4.0,4 available / 51 sold,51.0,"May 22, 2024 05:44:45 PDT","TX, United States",Women

In [74]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   brand              1998 non-null   object
 1   title              2000 non-null   object
 2   type               1995 non-null   object
 3   price              2000 non-null   float64
 4   priceWithCurrency  2000 non-null   object
 5   available          1758 non-null   float64
 6   availableText      1989 non-null   object
 7   sold               1978 non-null   float64
 8   lastUpdated        1874 non-null   object
 9   itemLocation       2000 non-null   object
 10  gender             2000 non-null   object
dtypes: float64(3), object(8)
memory usage: 172.0+ KB

In [75]:
df.describe()

             price    available          sold
count  2000.000000  1758.000000   1978.000000
mean     43.187090    20.728669    632.473711
std      32.619625    56.781389   2470.055822
min       1.990000     2.000000      1.000000
25%      21.972500     5.000000     14.000000
50%      34.040000    10.000000     51.000000
75%      53.990000    10.000000    285.750000
max     299.990000   842.000000  54052.000000

In [76]:
df.describe(include="O")

,brand,title,type,priceWithCurrency,availableText,lastUpdated,itemLocation,gender
count,1998,2000,1995,2000,1989,1874,2000,2000
unique,401,1941,116,1164,1300,1831,447,2
top,Giorgio Armani,YSL Yves Saint Laurent Y Eau de Perfume Spray Cologne For Men 3.3 oz 100ML,Eau de Parfum,US $29.99/ea,More than 10 available / 2 sold,"May 24, 2024 10:26:59 PDT","Dallas, Texas, United States",Men
freq,72,4,847,38,12,5,267,1000

In [77]:
df.duplicated().sum()

np.int64(1)

As there is 1 duplicate row we need to drop it

In [78]:
df.drop_duplicates(inplace=True) # inplace true directly modifies the original df, else we had to assign droped df back to df.

In [79]:
df.duplicated().sum()

np.int64(0)

Handling Nulls

In [80]:
df.isnull().sum()

brand                  2
title                  0
type                   5
price                  0
priceWithCurrency      0
available            242
availableText         11
sold                  22
lastUpdated          125
itemLocation           0
gender                 0
dtype: int64

In [81]:
# Filtering the rows with null brand column
df.query("brand.isnull()")

,brand,title,type,price,priceWithCurrency,available,availableText,sold,lastUpdated,itemLocation,gender
567,NaN,Versace Pour Homme Oud Noir 3.4 oz EDP Cologne for Men New In Box,Eau de Parfum,55.16,US $55.16/ea,NaN,"Limited quantity available / 3,110 sold",3110.0,"May 24, 2024 07:53:50 PDT","Hackensack, New Jersey, United States",Men
1856,NaN,Bright Crystal de Versace Eau de Toilette 3.0 EE. UU. fl. oz. / Spray Mujer 90 ml-,NaN,29.99,US $29.99,NaN,2 disponibles / 3 vendidos,NaN,23 may 2024 02:42:14 EST,"Hamtramck, Michigan, Estados Unidos",Women

Since there are only 2 rows with no brands, quickly looked title and i found it's versace brand, i assigned brand as versace

In [82]:
# Assigning the brand as versace agter quick lookup
df.loc[df["title"].str.contains("Versace", case=False), "brand"] = "Versace"

In [83]:
df.loc[[567, 1856]]

,brand,title,type,price,priceWithCurrency,available,availableText,sold,lastUpdated,itemLocation,gender
567,Versace,Versace Pour Homme Oud Noir 3.4 oz EDP Cologne for Men New In Box,Eau de Parfum,55.16,US $55.16/ea,NaN,"Limited quantity available / 3,110 sold",3110.0,"May 24, 2024 07:53:50 PDT","Hackensack, New Jersey, United States",Men
1856,Versace,Bright Crystal de Versace Eau de Toilette 3.0 EE. UU. fl. oz. / Spray Mujer 90 ml-,NaN,29.99,US $29.99,NaN,2 disponibles / 3 vendidos,NaN,23 may 2024 02:42:14 EST,"Hamtramck, Michigan, Estados Unidos",Women

As you can see the brand name has been assigned successfully

In [84]:
# Fill missing values of type column with the mode
df["type"] = df["type"].fillna(df["type"].mode()[0])

In [85]:
# If the text says "Last One", fill the missing available count with 1
df.loc[df['available'].isnull() & df['availableText'].str.contains('Last One', case=False, na=False), 'available'] = 1

# Fill all remaining missing values in 'available' with the column's median (10)
df['available'] = df['available'].fillna(df['available'].median())

In [86]:
df.isnull().sum()

brand                  0
title                  0
type                   0
price                  0
priceWithCurrency      0
available              0
availableText         11
sold                  22
lastUpdated          125
itemLocation           0
gender                 0
dtype: int64

In [87]:
# Fill text column with a placeholder
df['availableText'] = df['availableText'].fillna('Unknown')

# Fill missing sales with 0
df['sold'] = df['sold'].fillna(0)

In [88]:
df['lastUpdated'] = pd.to_datetime(df['lastUpdated'], errors='coerce')

C:\Users\bishw\AppData\Local\Temp\ipykernel_11048\3532019011.py:1: FutureWarning: Parsed string "May 24, 2024 10:03:04 PDT" included an un-recognized timezone "PDT". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  df['lastUpdated'] = pd.to_datetime(df['lastUpdated'], errors='coerce')

In [89]:
df.isnull().sum()

brand                  0
title                  0
type                   0
price                  0
priceWithCurrency      0
available              0
availableText          0
sold                   0
lastUpdated          276
itemLocation           0
gender                 0
dtype: int64