In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv("../datasets/social_media_user_behavior.csv")
pd.set_option('display.max_columns', None) #not to limit the number of columns displayed
pd.set_option('display.width', None) #adjust the output width

In [12]:
df

,user_id,age,gender,country,profession,primary_platform,platforms_used_count,daily_usage_hours,sessions_per_day,avg_session_duration_min,preferred_device,peak_usage_time,followers_count,following_count,posts_per_week,likes_given_per_day,comments_per_day,shares_per_day,dms_sent_per_day,preferred_content_type,scroll_speed,ad_click_rate,purchased_via_social_media,monthly_spend_via_social_usd,primary_purpose,sleep_disruption,self_reported_mental_health_score,screen_time_concern,notification_frequency,privacy_setting,influencer_status,account_join_date,mood_while_scrolling,takes_social_media_breaks
0,USR00001,30,Female,UK,Doctor,Facebook,1,1.6,2,48.0,Smartphone,Late Night (12am+),353,99,1,17,1,3,8,Photos,Medium,0.089,Yes,67.72,Entertainment,No impact,3.9,No,Do Not Disturb,Friends Only,No,2022-10-21,Neutral,No
1,USR00002,25,Male,USA,Entrepreneur,Instagram,2,2.4,5,28.8,Smartphone,Afternoon (12-4pm),276,514,2,28,3,4,16,Memes,Medium,0.065,Yes,1.62,News & Updates,Moderate impact,4.2,No,Selected,Public,No,2024-12-03,Neutral,Yes
2,USR00003,32,Male,UAE,Freelancer,TikTok,5,0.5,6,5.0,Smartphone,Night (9pm-12am),203,422,3,26,4,2,7,Videos,Slow,0.278,No,0.00,Learning,Mild impact,4.8,Yes,Always On,Friends Only,No,2023-03-29,Happy,Yes
3,USR00004,39,Prefer not to say,Pakistan,Other,TikTok,4,3.0,7,25.7,Smartphone,Evening (6-9pm),29083,474,1,16,3,1,12,Entertainment,Fast,0.094,No,0.00,Entertainment,Mild impact,7.9,Somewhat,Always On,Public,Yes,2024-04-26,Happy,No
4,USR00005,25,Male,UK,Other,YouTube,3,3.9,7,33.4,Tablet,Evening (6-9pm),104,197,2,27,7,4,7,Photos,Fast,0.075,No,0.00,Entertainment,Mild impact,6.5,No,Do Not Disturb,Public,No,2023-09-08,Inspired,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,USR01996,35,Female,Pakistan,Designer,TikTok,5,2.0,7,17.1,Smartphone,Morning (6-10am),27,703,5,26,5,1,10,Videos,Medium,0.162,Sometimes,40.76,Learning,Moderate impact,9.0,Yes,Off,Friends Only,No,2022-03-29,Happy,Yes
1996,USR01997,26,Male,USA,Researcher,Facebook,5,3.9,4,58.5,Smartphone,Late Night (12am+),398,254,3,31,2,3,6,Videos,Fast,0.089,Sometimes,37.04,Business/Marketing,No impact,4.1,Yes,Selected,Friends Only,No,2023-02-28,Stressed,Yes
1997,USR01998,19,Female,Pakistan,Engineer,Facebook,2,7.1,7,60.9,Laptop,Evening (6-9pm),284,298,4,16,3,1,5,Entertainment,Fast,0.270,Yes,19.26,Learning,Moderate impact,7.7,Somewhat,Selected,Friends Only,No,2024-11-26,Stressed,Occasionally
1998,USR01999,25,Male,India,Researcher,TikTok,4,4.9,6,49.0,Laptop,Night (9pm-12am),767,153,1,24,5,4,9,Educational,Medium,0.150,Sometimes,67.37,Business/Marketing,Moderate impact,5.1,Yes,Always On,Public,No,2024-01-10,Happy,No
1999,USR02000,21,Male,Pakistan,Entrepreneur,TikTok,5,2.8,4,42.0,Laptop,Night (9pm-12am),223,146,4,16,6,0,9,Memes,Fast,0.269,No,0.00,Socializing,Mild impact,6.8,Yes,Off,Friends Only,No,2024-03-05,Neutral,Occasionally

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 34 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   user_id                            2000 non-null   object
 1   age                                2000 non-null   int64
 2   gender                             2000 non-null   object
 3   country                            2000 non-null   object
 4   profession                         2000 non-null   object
 5   primary_platform                   2000 non-null   object
 6   platforms_used_count               2000 non-null   int64
 7   daily_usage_hours                  2000 non-null   float64
 8   sessions_per_day                   2000 non-null   int64
 9   avg_session_duration_min           2000 non-null   float64
 10  preferred_device                   2000 non-null   object
 11  peak_usage_time                    2000 non-null   object
 12  followers_count                    2000 non-null   int64
 13  following_count                    2000 non-null   int64
 14  posts_per_week                     2000 non-null   int64
 15  likes_given_per_day                2000 non-null   int64
 16  comments_per_day                   2000 non-null   int64
 17  shares_per_day                     2000 non-null   int64
 18  dms_sent_per_day                   2000 non-null   int64
 19  preferred_content_type             2000 non-null   object
 20  scroll_speed                       2000 non-null   object
 21  ad_click_rate                      2000 non-null   float64
 22  purchased_via_social_media         2000 non-null   object
 23  monthly_spend_via_social_usd       2000 non-null   float64
 24  primary_purpose                    2000 non-null   object
 25  sleep_disruption                   2000 non-null   object
 26  self_reported_mental_health_score  2000 non-null   float64
 27  screen_time_concern                2000 non-null   object
 28  notification_frequency             2000 non-null   object
 29  privacy_setting                    2000 non-null   object
 30  influencer_status                  2000 non-null   object
 31  account_join_date                  2000 non-null   object
 32  mood_while_scrolling               2000 non-null   object
 33  takes_social_media_breaks          2000 non-null   object
dtypes: float64(5), int64(10), object(19)
memory usage: 531.4+ KB

In [5]:
df.describe()

,age,platforms_used_count,daily_usage_hours,sessions_per_day,avg_session_duration_min,followers_count,following_count,posts_per_week,likes_given_per_day,comments_per_day,shares_per_day,dms_sent_per_day,ad_click_rate,monthly_spend_via_social_usd,self_reported_mental_health_score
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2.000000e+03,2000.0000,2000.000000,2000.000000,2000.000000,2000.000000,2000.00000,2000.000000,2000.000000,2000.00000
mean,26.986000,3.010000,2.990650,5.024500,47.547400,4.153738e+03,513.9985,2.964000,19.883000,3.991500,1.988500,8.02600,0.130048,22.618225,6.17115
std,7.649775,1.431756,1.858501,2.249985,51.104393,4.793563e+04,851.8179,1.679915,4.389527,1.997354,1.413636,2.77618,0.094675,33.884331,1.74912
min,13.000000,1.000000,0.500000,1.000000,3.300000,0.000000e+00,4.0000,0.000000,6.000000,0.000000,0.000000,1.00000,0.001000,0.000000,1.00000
25%,22.000000,2.000000,1.600000,3.000000,18.975000,2.017500e+02,109.0000,2.000000,17.000000,3.000000,1.000000,6.00000,0.058750,0.000000,4.90000
50%,27.000000,3.000000,2.600000,5.000000,34.000000,6.880000e+02,249.0000,3.000000,20.000000,4.000000,2.000000,8.00000,0.108000,7.315000,6.20000
75%,32.000000,4.000000,3.900000,6.000000,56.000000,2.320500e+03,580.0000,4.000000,23.000000,5.000000,3.000000,10.00000,0.182000,33.632500,7.40000
max,57.000000,5.000000,12.000000,15.000000,594.000000,2.110323e+06,10000.0000,10.000000,38.000000,11.000000,8.000000,19.00000,0.585000,266.370000,10.00000

In [4]:
df.isnull().sum()

user_id                              0
age                                  0
gender                               0
country                              0
profession                           0
primary_platform                     0
platforms_used_count                 0
daily_usage_hours                    0
sessions_per_day                     0
avg_session_duration_min             0
preferred_device                     0
peak_usage_time                      0
followers_count                      0
following_count                      0
posts_per_week                       0
likes_given_per_day                  0
comments_per_day                     0
shares_per_day                       0
dms_sent_per_day                     0
preferred_content_type               0
scroll_speed                         0
ad_click_rate                        0
purchased_via_social_media           0
monthly_spend_via_social_usd         0
primary_purpose                      0
sleep_disruption                     0
self_reported_mental_health_score    0
screen_time_concern                  0
notification_frequency               0
privacy_setting                      0
influencer_status                    0
account_join_date                    0
mood_while_scrolling                 0
takes_social_media_breaks            0
dtype: int64